set(_AMENT_PACKAGE_NAME "environment_builder")
set(environment_builder_VERSION "0.0.0")
set(environment_builder_MAINTAINER "pedro <pedrosaman96@gmail.com>")
set(environment_builder_BUILD_DEPENDS "environment_interface" "moveit_task_constructor_core" "moveit_ros_planning_interface" "rclcpp" "moveit_visual_tools")
set(environment_builder_BUILDTOOL_DEPENDS "ament_cmake")
set(environment_builder_BUILD_EXPORT_DEPENDS "environment_interface" "moveit_task_constructor_core" "moveit_ros_planning_interface" "rclcpp" "moveit_visual_tools")
set(environment_builder_BUILDTOOL_EXPORT_DEPENDS )
set(environment_builder_EXEC_DEPENDS "environment_interface" "moveit_task_constructor_core" "moveit_ros_planning_interface" "rclcpp" "moveit_visual_tools")
set(environment_builder_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(environment_builder_GROUP_DEPENDS )
set(environment_builder_MEMBER_OF_GROUPS )
set(environment_builder_DEPRECATED "")
set(environment_builder_EXPORT_TAGS)
list(APPEND environment_builder_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
