set(_AMENT_PACKAGE_NAME "environment_interface")
set(environment_interface_VERSION "0.0.0")
set(environment_interface_MAINTAINER "pedro <pedrosaman96@gmail.com>")
set(environment_interface_BUILD_DEPENDS "rosidl_default_generators" "moveit_visual_tools" "std_msgs" "moveit_task_constructor_core" "moveit_ros_planning_interface" "rclcpp" "action_msgs")
set(environment_interface_BUILDTOOL_DEPENDS "ament_cmake")
set(environment_interface_BUILD_EXPORT_DEPENDS "moveit_visual_tools" "std_msgs" "moveit_task_constructor_core" "moveit_ros_planning_interface" "rclcpp" "action_msgs")
set(environment_interface_BUILDTOOL_EXPORT_DEPENDS )
set(environment_interface_EXEC_DEPENDS "rosidl_default_runtime" "moveit_visual_tools" "std_msgs" "moveit_task_constructor_core" "moveit_ros_planning_interface" "rclcpp" "action_msgs")
set(environment_interface_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(environment_interface_GROUP_DEPENDS )
set(environment_interface_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(environment_interface_DEPRECATED "")
set(environment_interface_EXPORT_TAGS)
list(APPEND environment_interface_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
