set(_AMENT_PACKAGE_NAME "robot_movement_tester")
set(robot_movement_tester_VERSION "0.0.0")
set(robot_movement_tester_MAINTAINER "pedro <pedrosaman96@gmail.com>")
set(robot_movement_tester_BUILD_DEPENDS "moveit_ros_planning_interface" "rclcpp")
set(robot_movement_tester_BUILDTOOL_DEPENDS "ament_cmake")
set(robot_movement_tester_BUILD_EXPORT_DEPENDS "moveit_ros_planning_interface" "rclcpp")
set(robot_movement_tester_BUILDTOOL_EXPORT_DEPENDS )
set(robot_movement_tester_EXEC_DEPENDS "moveit_ros_planning_interface" "rclcpp")
set(robot_movement_tester_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(robot_movement_tester_GROUP_DEPENDS )
set(robot_movement_tester_MEMBER_OF_GROUPS )
set(robot_movement_tester_DEPRECATED "")
set(robot_movement_tester_EXPORT_TAGS)
list(APPEND robot_movement_tester_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
