set(_AMENT_PACKAGE_NAME "manipulation_task_constructor")
set(manipulation_task_constructor_VERSION "0.0.0")
set(manipulation_task_constructor_MAINTAINER "user <youremail@domain.com>")
set(manipulation_task_constructor_BUILD_DEPENDS "environment_interface" "moveit_task_constructor_core" "moveit_ros_planning_interface" "rclcpp" "moveit_visual_tools")
set(manipulation_task_constructor_BUILDTOOL_DEPENDS "ament_cmake")
set(manipulation_task_constructor_BUILD_EXPORT_DEPENDS "environment_interface" "moveit_task_constructor_core" "moveit_ros_planning_interface" "rclcpp" "moveit_visual_tools")
set(manipulation_task_constructor_BUILDTOOL_EXPORT_DEPENDS )
set(manipulation_task_constructor_EXEC_DEPENDS "environment_interface" "moveit_task_constructor_core" "moveit_ros_planning_interface" "rclcpp" "moveit_visual_tools")
set(manipulation_task_constructor_TEST_DEPENDS "ament_lint_auto" "ament_lint_common")
set(manipulation_task_constructor_GROUP_DEPENDS )
set(manipulation_task_constructor_MEMBER_OF_GROUPS )
set(manipulation_task_constructor_DEPRECATED "")
set(manipulation_task_constructor_EXPORT_TAGS)
list(APPEND manipulation_task_constructor_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
