set(_AMENT_PACKAGE_NAME "denso_cobotta_moveit_config")
set(denso_cobotta_moveit_config_VERSION "0.3.0")
set(denso_cobotta_moveit_config_MAINTAINER "pedro <pedro@pedro.com>")
set(denso_cobotta_moveit_config_BUILD_DEPENDS )
set(denso_cobotta_moveit_config_BUILDTOOL_DEPENDS "ament_cmake")
set(denso_cobotta_moveit_config_BUILD_EXPORT_DEPENDS )
set(denso_cobotta_moveit_config_BUILDTOOL_EXPORT_DEPENDS )
set(denso_cobotta_moveit_config_EXEC_DEPENDS "moveit_ros_move_group" "moveit_kinematics" "moveit_planners" "moveit_simple_controller_manager" "joint_state_publisher" "joint_state_publisher_gui" "tf2_ros" "xacro" "controller_manager" "denso_cobotta_description" "moveit_configs_utils" "moveit_ros_move_group" "moveit_ros_visualization" "moveit_ros_warehouse" "moveit_setup_assistant" "robot_state_publisher" "rviz2" "rviz_common" "rviz_default_plugins" "tf2_ros" "warehouse_ros_mongo" "xacro")
set(denso_cobotta_moveit_config_TEST_DEPENDS )
set(denso_cobotta_moveit_config_GROUP_DEPENDS )
set(denso_cobotta_moveit_config_MEMBER_OF_GROUPS )
set(denso_cobotta_moveit_config_DEPRECATED "")
set(denso_cobotta_moveit_config_EXPORT_TAGS)
list(APPEND denso_cobotta_moveit_config_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
